"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar & Shell
    activeNode: "ACTIVE NODE",
    hubConsole: "HUB CONSOLE",
    addBotServer: "ADD BOT SERVER",
    emergencyLockdown: "EMERGENCY LOCKDOWN",
    operatorLevel: "LEVEL: HIGH-CLEARANCE",
    shieldActive: "SHIELD: ACTIVE",
    ping: "PING",
    systemEvents: "SYSTEM EVENTS",
    clearAll: "Clear All",
    noEvents: "No critical reports for",
    systemLockdownTitle: "SYSTEM LOCKDOWN",
    systemLockdownDesc: "Manual safety override engaged. All active tunnels have been frozen.",
    enterPin: "Enter Operator Override PIN",
    invalidPin: "INVALID BYPASS KEY CODE",
    deactivateSheath: "DEACTIVATE SHEATH",
    defaultPinMsg: "DEFAULT SYSTEM RECOVERY PIN: 0000 OR 1337",

    // Nav Items
    navCommandCenter: "Command Center",
    navDiscordSettings: "Discord Settings",
    navAiAssistant: "AI Core Assistant",
    navAuditLogs: "Audit Logs",

    // Dashboard Home
    controlCenterTitle: "SYSTEM CONTROL CENTER",
    controlCenterSub: "Real-time Node Telemetry & Threat Defense",
    aiStateOnline: "SYNAPSE-ONLINE",
    aiStateLabel: "AI CORE STATE",
    secScoreLabel: "Global Security Score",
    secScoreSecured: "SYSTEM SECURED",
    shieldStatusLabel: "Shield Status",
    shieldStatusActive: "ACTIVE / PROTECTED",
    monitoredMembersLabel: "Monitored Members",
    monitoredMembersSub: "real-time synchronization",
    activeAnomaliesLabel: "Active Anomalies",
    activeAnomaliesSub: "mitigated: 99.4%",
    activeThreatsTitle: "Active Threat Gateways",
    secureStack: "SECURE STACK",
    clusterHardwareTitle: "Cluster Hardware Health",
    cpuLoad: "CPU Load",
    ramBuffer: "Memory Buffer",
    netPort: "Inbound Socket Port",
    firewallPort: "Firewall Port",
    proxyRouting: "Proxy Routing",
    secureStatus: "SECURE",
    tunnelingStatus: "TUNNELING",
    liveIncidentTitle: "Live Security Incident Feed",
    streamingLogs: "Streaming logs live",
    thLogId: "Log ID",
    thTimestamp: "Timestamp",
    thOperator: "Operator/Origin",
    thAction: "Action Payload",
    thCategory: "Group Category",
    thSeverity: "Threat Severity",
    thDetails: "Raw Details",
    noLogsMatch: "No logs matching query criteria found.",

    // Discord Settings
    discordSettingsTitle: "DISCORD NODE MANAGEMENT",
    discordSettingsSub: "Configure discord integration bridges, roles, and automated moderators",
    discMembers: "Discord Members",
    discMembersHour: "+18 this hour",
    activeChannels: "Active Channels",
    categoriesMonitored: "2 categories monitored",
    verifiedMembers: "Verified Members",
    successRate: "91.2% Success Rate",
    securityTier: "Security Tier",
    maxShield: "MAX SHIELD",
    antiNukeActive: "Anti-Nuke Active",
    authGatewayConfigs: "Authorization & Gateway Configurations",
    ticketQueueTitle: "Support Ticket Queue",
    allTicketsResolved: "ALL TICKETS RESOLVED",
    resetQueueSim: "Reset Queue Simulator",
    welcomeTextEditor: "Embed Welcome Text Editor",
    welcomeTextSub: "Welcome {user} to SecurityBot System X server! Please complete verification via link to obtain roles.",
    welcomeTextVariables: "Variables: {user}, {server}",
    autoSaveActive: "Auto-Save Active",
    oauthGateTitle: "OAuth2 Verification Gate",
    oauthGateDesc: "Forces new joins to verify via third-party web panel before getting access roles.",
    welcomeBroadcastTitle: "Automated Welcome Broadcasts",
    welcomeBroadcastDesc: "Embeds customizable greeting content in general chat channels on user join.",
    loggingSyncTitle: "Granular Logging Sync",
    loggingSyncDesc: "Forwards deleted messages, channel modifications, and role updates to audit channels.",
    inviteFilterTitle: "Anti-Invite Link Filter",
    inviteFilterDesc: "Revokes invite links to other Discord servers generated by default users.",
    diagTunnelsTitle: "Security Bot Diagnostics Tunnels",
    diagTunnelsDesc: "Streams critical threat metrics directly to the System X dashboard panel.",

    // AI Assistant
    aiAssistantTitle: "AI SECURITY CORE ASSISTANT",
    aiAssistantSub: "Command AI Core to conduct diagnostics audits and audit risk thresholds",
    suggestedTasks: "Suggested Diagnostic Core Tasks",
    runAuditTitle: "Run Server Audit",
    runAuditDesc: "Scans active roles, invites, permissions structures.",
    leakScanTitle: "Leak Database Scan",
    leakScanDesc: "Checks credentials against compromised databases.",
    mitigationTitle: "Mitigation Guidelines",
    mitigationDesc: "Drafts rules presets for link filtering configurations.",
    aiPlaceholder: "Ask the AI Security Core to perform audits...",
    aiCoreAnalyzing: "AI core analyzing telemetry data...",

    // Audit Logs
    auditLogsTitle: "AUDIT LOG TELEMETRY",
    auditLogsSub: "Chronological records of all system state events, moderation actions, and user integrations",
    exportCsv: "EXPORT CSV",
    exportCsvSuccess: "EXPORTED CSV",
    exportJson: "EXPORT JSON",
    searchPlaceholder: "Search logs by ID, action, user, or details...",
    allCategories: "All Categories",
    catSecurity: "Security Only",
    catModeration: "Moderation Only",
    catSystem: "System Configurations",
    catVerification: "Verification Gates",
    catRoles: "Roles & Permissions",
    catChannels: "Channels Logging",
    allSeverities: "All Severities",
    sevCritical: "Critical Threats",
    sevHigh: "High Severity",
    sevMedium: "Medium Severity",
    sevLow: "Low Log"
  },
  ar: {
    // Sidebar & Shell
    activeNode: "الخادم النشط",
    hubConsole: "الكونسول الرئيسي",
    addBotServer: "إضافة البوت لخادم",
    emergencyLockdown: "إغلاق الطوارئ الكامل",
    operatorLevel: "مستوى التصريح: عالي السرية",
    shieldActive: "درع الحماية: نشط",
    ping: "الاستجابة",
    systemEvents: "أحداث النظام",
    clearAll: "مسح الكل",
    noEvents: "لا توجد بلاغات حرجة لـ",
    systemLockdownTitle: "إغلاق الطوارئ للنظام",
    systemLockdownDesc: "تم تفعيل التجاوز الأمني اليدوي. تم تجميد جميع مسارات الاتصال النشطة.",
    enterPin: "أدخل رمز التجاوز الأمني للمشغل",
    invalidPin: "رمز التجاوز غير صحيح",
    deactivateSheath: "إلغاء التجميد الأمني",
    defaultPinMsg: "رمز الاستعادة الافتراضي: 0000 أو 1337",

    // Nav Items
    navCommandCenter: "مركز التحكم",
    navDiscordSettings: "إعدادات ديسكورد",
    navAiAssistant: "المساعد الأمني الذكي",
    navAuditLogs: "سجل العمليات",

    // Dashboard Home
    controlCenterTitle: "مركز التحكم بالنظام",
    controlCenterSub: "القياس الأمني الفوري والحماية ضد التهديدات",
    aiStateOnline: "الذكاء الاصطناعي متصل",
    aiStateLabel: "حالة الذكاء الاصطناعي",
    secScoreLabel: "مؤشر الأمان العام",
    secScoreSecured: "النظام مؤمن بالكامل",
    shieldStatusLabel: "حالة درع الحماية",
    shieldStatusActive: "نشط / محمي",
    monitoredMembersLabel: "الأعضاء المراقبون",
    monitoredMembersSub: "مزامنة فورية نشطة",
    activeAnomaliesLabel: "التهديدات المكتشفة",
    activeAnomaliesSub: "تم احتواء 99.4%",
    activeThreatsTitle: "بوابات التهديد النشطة",
    secureStack: "حزمة الحماية",
    clusterHardwareTitle: "سلامة مكونات الخادم",
    cpuLoad: "استهلاك المعالج",
    ramBuffer: "ذاكرة الوصول العشوائي",
    netPort: "منفذ البيانات الواردة",
    firewallPort: "جدار الحماية",
    proxyRouting: "توجيه الوكيل",
    secureStatus: "مؤمن",
    tunnelingStatus: "إنشاء مسار آمن",
    liveIncidentTitle: "تغذية الأحداث الأمنية الفورية",
    streamingLogs: "يتم بث السجلات مباشرة",
    thLogId: "معرف السجل",
    thTimestamp: "الطابع الزمني",
    thOperator: "المشغل/المصدر",
    thAction: "الإجراء المتخذ",
    thCategory: "الفئة",
    thSeverity: "مستوى الخطورة",
    thDetails: "التفاصيل الكاملة",
    noLogsMatch: "لم يتم العثور على سجلات تطابق البحث.",

    // Discord Settings
    discordSettingsTitle: "إدارة خادم الديسكورد",
    discordSettingsSub: "تكوين بوابات التحقق، الرتب، والمشرفين التلقائيين للبوت",
    discMembers: "أعضاء السيرفر",
    discMembersHour: "+18 هذه الساعة",
    activeChannels: "القنوات النشطة",
    categoriesMonitored: "مراقبة فئتين من القنوات",
    verifiedMembers: "الأعضاء الموثقون",
    successRate: "نسبة توثيق 91.2%",
    securityTier: "مستوى الأمان",
    maxShield: "الحماية القصوى",
    antiNukeActive: "حماية الأنظمة الحساسة مفعلة",
    authGatewayConfigs: "إعدادات المصادقة وبوابات الدخول",
    ticketQueueTitle: "تذاكر الدعم الفني المعلقة",
    allTicketsResolved: "تم حل جميع التذاكر بالكامل",
    resetQueueSim: "إعادة تعيين المحاكي",
    welcomeTextEditor: "محرر نص الترحيب المضمن",
    welcomeTextSub: "مرحباً بك {user} في خادم SecurityBot System X! يرجى إكمال التوثيق عبر الرابط للحصول على الرتب.",
    welcomeTextVariables: "المتغيرات المتاحة: {user}, {server}",
    autoSaveActive: "الحفظ التلقائي نشط",
    oauthGateTitle: "بوابة تحقق OAuth2",
    oauthGateDesc: "إجبار الأعضاء الجدد على التوثيق عبر لوحة تحكم الويب قبل الحصول على رتبة دخول السيرفر.",
    welcomeBroadcastTitle: "رسائل ترحيب تلقائية",
    welcomeBroadcastDesc: "إرسال رسائل ترحيب مخصصة في القنوات العامة عند انضمام أعضاء جدد.",
    loggingSyncTitle: "مزامنة السجلات التفصيلية",
    loggingSyncDesc: "إرسال الرسائل المحذوفة وتعديل القنوات وتحديثات الرتب إلى قنوات التدقيق المخصصة.",
    inviteFilterTitle: "تصفية روابط الدعوة",
    inviteFilterDesc: "حظر وإلغاء روابط الدعوة لسيرفرات ديسكورد أخرى المنشأة بواسطة الأعضاء العاديين.",
    diagTunnelsTitle: "قنوات تشخيص البوت الأمنية",
    diagTunnelsDesc: "بث مقاييس التهديد الهامة مباشرة إلى لوحة تحكم النظام الرئيسي.",

    // AI Assistant
    aiAssistantTitle: "مساعد الذكاء الاصطناعي الأمني",
    aiAssistantSub: "توجيه نظام الذكاء الاصطناعي لإجراء فحوصات تشخيصية وتقييم مستويات المخاطر",
    suggestedTasks: "المهام التشخيصية المقترحة للذكاء الاصطناعي",
    runAuditTitle: "تشغيل فحص الخادم",
    runAuditDesc: "فحص رتب السيرفر، الدعوات، وصلاحيات القنوات.",
    leakScanTitle: "فحص تسريب البيانات",
    leakScanDesc: "فحص بيانات الاعتماد والمشغلين ضد قواعد البيانات المسربة.",
    mitigationTitle: "إرشادات الاحتواء",
    mitigationDesc: "صياغة قواعد وقائية مرنة لتصفيات الروابط المشبوهة.",
    aiPlaceholder: "اسأل المساعد الذكاء الاصطناعي الأمني لإجراء الفحوصات الأمنية...",
    aiCoreAnalyzing: "مستكشف الذكاء الاصطناعي يقوم بتحليل البيانات الحالية للشبكة...",

    // Audit Logs
    auditLogsTitle: "سجل العمليات والتدقيق الأمني",
    auditLogsSub: "سجل زمني لجميع أحداث النظام، قرارات الإشراف، والتكامل مع بوابات التوثيق الخارجية",
    exportCsv: "تصدير CSV",
    exportCsvSuccess: "تم تصدير CSV بنجاح",
    exportJson: "تصدير JSON",
    searchPlaceholder: "ابحث في السجلات عن طريق المعرف، الإجراء، المشغل، أو التفاصيل...",
    allCategories: "جميع الفئات",
    catSecurity: "الأمن فقط",
    catModeration: "الإشراف فقط",
    catSystem: "إعدادات النظام",
    catVerification: "بوابات التحقق",
    catRoles: "الرتب والصلاحيات",
    catChannels: "سجلات القنوات",
    allSeverities: "جميع مستويات الخطورة",
    sevCritical: "تهديدات حرجة جداً",
    sevHigh: "خطورة عالية",
    sevMedium: "خطورة متوسطة",
    sevLow: "سجل عادي"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("system-lang") as Language;
      if (stored === "en" || stored === "ar") {
        setLangState(stored);
      }
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    if (typeof window !== "undefined") {
      localStorage.setItem("system-lang", newLang);
      // Dispatch storage event to notify other tabs/components
      window.dispatchEvent(new Event("storage"));
    }
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
