"use client";

import React, { useState } from "react";
import { MessageSquare, Users, ShieldAlert, Check, ToggleLeft, ToggleRight, X, Play } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface Ticket {
  id: string;
  user: string;
  reason: string;
  category: "Verification" | "Report" | "Admin Access";
  time: string;
}

const initialTickets: Ticket[] = [
  { id: "TCK-401", user: "GamerPro#1002", reason: "Failing OAuth2 verification callback.", category: "Verification", time: "3m ago" },
  { id: "TCK-400", user: "Tox Hunter#3990", reason: "Reporting spam bots in #general-chat.", category: "Report", time: "12m ago" },
  { id: "TCK-399", user: "DevMod_Alpha", reason: "API key validation mismatch on Webhook sync.", category: "Admin Access", time: "45m ago" }
];

export default function DiscordManagement() {
  const [toggles, setToggles] = useState({
    verificationGate: true,
    welcomeSystem: false,
    auditLogging: true,
    inviteBlock: false,
    moderationLogs: true
  });

  const [tickets, setTickets] = useState<Ticket[]>(initialTickets);
  const [welcomeText, setWelcomeText] = useState("Welcome {user} to SecurityBot System X server! Please complete verification via link to obtain roles.");

  const handleToggle = (key: keyof typeof toggles) => {
    setToggles(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleResolveTicket = (id: string) => {
    setTickets(prev => prev.filter(t => t.id !== id));
  };

  return (
    <div className="space-y-8">
      {/* SECTION HEADER */}
      <div>
        <h1 className="text-2xl font-bold text-white font-mono tracking-wider">DISCORD NODE MANAGEMENT</h1>
        <p className="text-xs text-gray-400 font-mono uppercase tracking-widest">Configure discord integration bridges, roles, and automated moderators</p>
      </div>

      {/* OVERVIEW PANEL */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="glass-panel p-5 rounded-xl border-white/5 space-y-1">
          <p className="text-[10px] text-gray-500 font-mono uppercase tracking-widest">Discord Members</p>
          <p className="text-2xl font-bold text-white font-mono">12,891</p>
          <p className="text-[10px] text-cyber-blue font-mono font-semibold">+18 this hour</p>
        </div>
        <div className="glass-panel p-5 rounded-xl border-white/5 space-y-1">
          <p className="text-[10px] text-gray-500 font-mono uppercase tracking-widest">Active Channels</p>
          <p className="text-2xl font-bold text-white font-mono">42</p>
          <p className="text-[10px] text-gray-500 font-mono">2 categories monitored</p>
        </div>
        <div className="glass-panel p-5 rounded-xl border-white/5 space-y-1">
          <p className="text-[10px] text-gray-500 font-mono uppercase tracking-widest">Verified Members</p>
          <p className="text-2xl font-bold text-cyber-green font-mono">11,760</p>
          <p className="text-[10px] text-cyber-green font-mono font-semibold">91.2% Success Rate</p>
        </div>
        <div className="glass-panel p-5 rounded-xl border-white/5 space-y-1">
          <p className="text-[10px] text-gray-500 font-mono uppercase tracking-widest">Security Tier</p>
          <p className="text-2xl font-bold text-cyber-purple font-mono">MAX SHIELD</p>
          <p className="text-[10px] text-cyber-purple font-mono font-semibold">Anti-Nuke Active</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Toggles settings card */}
        <div className="glass-panel p-6 rounded-2xl border-white/5 bg-black/40 lg:col-span-2 space-y-6">
          <h3 className="font-bold text-white font-mono text-xs uppercase tracking-widest border-b border-white/5 pb-3">
            Authorization & Gateway Configurations
          </h3>

          <div className="space-y-4">
            {[
              { key: "verificationGate", title: "OAuth2 Verification Gate", desc: "Forces new joins to verify via third-party web panel before getting access roles." },
              { key: "welcomeSystem", title: "Automated Welcome Broadcasts", desc: "Embeds customizable greeting content in general chat channels on user join." },
              { key: "auditLogging", title: "Granular Logging Sync", desc: "Forwards deleted messages, channel modifications, and role updates to audit channels." },
              { key: "inviteBlock", title: "Anti-Invite Link Filter", desc: "Revokes invite links to other Discord servers generated by default users." },
              { key: "moderationLogs", title: "Security Bot Diagnostics Tunnels", desc: "Streams critical threat metrics directly to the System X dashboard panel." }
            ].map((item) => (
              <div key={item.key} className="flex justify-between items-start gap-6 p-4 rounded-xl bg-white/5 border border-white/5 hover:border-white/10 transition-colors">
                <div className="space-y-1">
                  <h4 className="font-bold text-xs text-white font-mono">{item.title}</h4>
                  <p className="text-[11px] text-gray-400 leading-normal">{item.desc}</p>
                </div>
                <button 
                  onClick={() => handleToggle(item.key as any)}
                  className="text-cyber-blue shrink-0 cursor-pointer"
                >
                  {toggles[item.key as keyof typeof toggles] ? (
                    <ToggleRight className="h-9 w-9 text-cyber-blue" />
                  ) : (
                    <ToggleLeft className="h-9 w-9 text-gray-600" />
                  )}
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Ticket simulator list */}
        <div className="space-y-6">
          {/* Support Ticket Queue */}
          <div className="glass-panel p-6 rounded-2xl border-white/5 bg-black/40 space-y-4 flex flex-col h-[380px] shadow-[0_0_20px_rgba(6,182,212,0.02)]">
            <h3 className="font-bold text-white font-mono text-xs uppercase tracking-widest border-b border-white/5 pb-3">
              Support Ticket Queue
            </h3>

            <div className="flex-1 overflow-y-auto space-y-3 pr-1">
              <AnimatePresence initial={false}>
                {tickets.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-full text-center space-y-2 py-8 text-gray-500">
                    <Check className="h-8 w-8 text-cyber-green animate-bounce" />
                    <p className="text-xs font-mono">ALL TICKETS RESOLVED</p>
                    <button 
                      onClick={() => setTickets(initialTickets)}
                      className="text-[10px] text-cyber-blue hover:underline cursor-pointer"
                    >
                      Reset Queue Simulator
                    </button>
                  </div>
                ) : (
                  tickets.map((tck) => (
                    <motion.div 
                      key={tck.id}
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, x: 50 }}
                      className="p-3 rounded-lg bg-white/5 border border-white/5 flex justify-between items-start gap-3 relative group"
                    >
                      <div className="space-y-1">
                        <div className="flex items-center gap-2">
                          <span className="text-[10px] font-bold text-white font-mono">{tck.user}</span>
                          <span className="text-[9px] font-mono px-1 py-0.2 bg-white/10 rounded text-gray-400">{tck.category}</span>
                        </div>
                        <p className="text-[11px] text-gray-400 leading-normal">{tck.reason}</p>
                        <p className="text-[9px] text-gray-600 font-mono">{tck.time}</p>
                      </div>

                      <button 
                        onClick={() => handleResolveTicket(tck.id)}
                        className="p-1 rounded bg-cyan-950/40 hover:bg-cyan-950/60 border border-cyber-blue/30 text-cyber-blue hover:text-white transition-all cursor-pointer"
                      >
                        <Check className="h-3 w-3" />
                      </button>
                    </motion.div>
                  ))
                )}
              </AnimatePresence>
            </div>
          </div>

          {/* Welcome embeds editor */}
          <div className="glass-panel p-6 rounded-2xl border-white/5 bg-black/40 space-y-4">
            <h3 className="font-bold text-white font-mono text-xs uppercase tracking-widest border-b border-white/5 pb-3">
              Embed Welcome Text Editor
            </h3>
            <textarea
              rows={3}
              value={welcomeText}
              onChange={(e) => setWelcomeText(e.target.value)}
              className="w-full bg-black/60 border border-white/10 rounded-lg p-3 text-xs outline-none focus:border-cyber-blue font-mono text-gray-300 resize-none"
            />
            <div className="flex justify-between items-center text-[10px] font-mono">
              <span className="text-gray-500">Variables: {"{user}"}, {"{server}"}</span>
              <span className="text-cyber-blue flex items-center gap-1"><Play className="h-3 w-3" /> Auto-Save Active</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
